version: '3.3'
services:
  mysql-db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      # <Port exposed> : <MySQL Port running inside container>
      - '3306:3306'
    volumes:
      - db:/var/lib/mysql

volumes:
  db:
